name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - name: Run a multi-line script
        run: |
          npm install
          npx browserslist@latest --update-db
          npx nx run-many --all --target=lint
          npx nx run-many --all --target=test --coverage
          npx nx run-many --all --target=build
